#page title
page_title                                : TimeFinder - Day Planner                                        # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1347447233                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : presskit.html                             # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
privacy_policy_link                       : privacy_policy.html                       # CUSTOM
tos_link                                  : terms_and_conditions.html                 # CUSTOM

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Daily planning made simple, on iPhone, iPad and Mac. 

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Luke Memet                            
your_link                                 : https://www.linkedin.com/in/lukememet/                  
your_city                                 : New Jersey, USA                                
email_address                             : luke@timefinder.app
facebook_username                         :                                           
instagram_username                        : timefinderapp
twitter_username                          : timefinder
github_username                           : 
youtube_username                          : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :
  
  
  - title                                 : Effortless visual planning
    description                           : TimeFinder's sleek and intuitive interface makes managing your busy schedule a breeze, letting you focus on what truly matters.
    fontawesome_icon_name                 : list

  - title                                 : Personalized Time-Blocking
    description                           : Customize TimeFinder to reflect your style and preferences with adjustable time intervals, color-coded tasks, and personalized lists.
    fontawesome_icon_name                 : clock
    
  - title                                 : Integrated with your Calendar
    description                           : Bring harmony to your life by effortlessly merging your existing calendar events with TimeFinder, making it your go-to hub for daily planning.
    fontawesome_icon_name                 : calendar-days

  - title                                 : Available on iPhone, iPad, and Mac
    description                           : Enjoy seamless planning and data access on iPhone, iPad and Mac with cloud syncing.
    fontawesome_icon_name                 : mobile-screen-button
    
  - title                                 : Complements productivity tools
    description                           : Enhance your workflow by using TimeFinder in tandem with goal trackers, bullet journals, habit trackers, project management apps, and more.
    fontawesome_icon_name                 : arrows-rotate
  
  - title                                 : Built by someone who gets it
    description                           : TimeFinder was designed as an asset to users with ADHD, autism, dyslexia, & other neurodevelopmental disorders that benefit from tools that help with organization, planning, & time management.
    fontawesome_icon_name                 : hand-holding-heart


# Theme Settings
topbar_color                              : "#85EAFF"
topbar_transparency                       : .9                       # Actually opacity. DEFAULT 0.1
topbar_title_color                        : "#000000"

cover_image                               :                          # Default: assets/headerimage.png; Replace with alternative image path or image URL.
cover_overlay_color                       : "#85EAFF"
cover_overlay_transparency                : 0.5

device_color                              : black                    # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#CCF6FF"

link_color                                : "#1d63ea"

app_title_color                           : "#000000"
app_price_color                           : "#000000"
app_description_color                     : "#000000"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#F79C25"  # 1d63ea  
feature_icons_background_color            : "#FFFFFF"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#FFFFFF"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
